version: '3.8'


services:

  # Spring app
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hc_app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - kafka
      - postgres
      - redis

  # Data Base SQl
  postgres:
    image: postgres:15
    container_name: hc_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  # Redis
  redis:
    image: redis:7
    container_name: honey_redis
    ports:
      - "6379:6379"

  # Zookeeper
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: 'zookeeper'
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  # Apache Kafka
  kafka:
    image: bitnami/kafka:latest
    container_name: 'hc_kafka'
    ports:
      - 9092:9092
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://10.5.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper


  # Kafka UI
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: hc_kafka-ui
    restart: always
    ports:
      - "8085:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: ${KAFKA_CLUSTERS_0_NAME}
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: ${KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS}
    depends_on:
      - kafka