spring:
  application:
    name: "tests-service"

  #Apache Kafka
  kafka:
    bootstrap-servers: localhost:9092
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#    consumer:
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      group-id: answer-group
#      properties:
#        spring.json.trusted.packages: '*'

  #Data config
  datasource:
    url: jdbc:postgresql://localhost:5434/postgres
    username: user
    password: user
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: localhost
      port: 6379

  cache:
    redis:
      time-to-live: 1m

  jackson:
    serialization:
      write-dates-as-timestamps: false

  #Flyaway config
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

logging:
  level:
    org:
      springframework:
        security: debug
        web: debug
server:
  port: 8080


jwt:
  private-key: classpath:jwt/app.key
  public-key: classpath:jwt/app.pub
  ttl: 120m

app:
  cors:
    allowed-origins:
      -http://localhost:3000
    allowed-methods: GET,POST,PUT,DELETE
    allowed-headers: Authorization,Content-Type
    allow-credentials: true

