server:
  port: 0

spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false



  #Data config
  datasource:
    url: jdbc:postgresql://localhost:5434/postgres
    username: user
    password: user

  cache:
    redis:
      time-to-live: 1m
  data:
    redis:
      host: localhost
      port: 6379
  #Flyaway config
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  cloud:
    discovery:
      enabled: true
  application:
    name: "tests-service"

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000

# Eureka config
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org:
      springframework:
        security: debug
        web: debug