#Spring config
spring:
  application:
    name: tests-service
  datasource:
    url: jdbc:postgresql://localhost:5434/postgres
    username: user
    password: user

 # cloud:
  #  discovery:
   #   enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
# Server config
server:
  port: 8080

# Eureka config
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
logging:
  level:
    org.flywaydb: debug

