spring:
  application:
    name: "tests-service"

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

  # Postgres
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/postgres

    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  # Redis
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  cache:
    redis:
      time-to-live: 10m

  jackson:
    serialization:
      write-dates-as-timestamps: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: ${SERVER_PORT:8080}

jwt:
  private-key: classpath:${JWT_PRIVATE_KEY:jwt/app.key}
  public-key: classpath:${JWT_PUBLIC_KEY:jwt/app.pub}
  ttl: ${JWT_TTL:120m}

app:
  cors:
    allowed-origins:
      - http://localhost:3000
    allowed-methods: GET,POST,PUT,DELETE
    allowed-headers: Authorization,Content-Type
    allow-credentials: true

logging:
  level:
    org:
      springframework:
        security: debug
        web: debug